- name: Deploy LankaMart App to Azure VM
  hosts: cloud
  become: yes
  vars:
    docker_user: "deliya123"
    image_name: "lanka-mart-app"
    image_tag: "1.0"
    container_name: "lanka-mart-app"
    port: "8081"

  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker service is running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Ensure Docker Python module is installed
      pip:
        name: docker

    - name: Pull Docker image from Docker Hub
      docker_image:
        name: "{{ docker_user }}/{{ image_name }}"
        tag: "{{ image_tag }}"
        source: pull

    - name: Stop existing container if running
      docker_container:
        name: "{{ container_name }}"
        state: absent
        force_kill: yes

    - name: Run Docker container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_user }}/{{ image_name }}:{{ image_tag }}"
        state: started
        ports:
          - "{{ port }}:80"
